version: "3.9"

networks:
  monitoring:

services:
  app:
    build:
      dockerfile: Dockerfile
    networks:
      - monitoring
    depends_on:
      - influxdb
      - grafana

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - monitoring
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin-password
      - DOCKER_INFLUXDB_INIT_BUCKET=performance-bucket
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=RQWlUg-S5QtgcPieJHU_WgWTDtDbqobm5nHF9txTxcpI9stRpg4yZCFp3hZmmna9Lnau-_Fn8haHO779iuujiw==

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin-password
    volumes:
      - ./environments/common/grafana/dashboards/influxdb-dashboard.json:/var/lib/grafana/dashboards/influxdb-dashboard.json
      - ./environments/common/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./environments/common/grafana/influx-datasource.yml:/etc/grafana/provisioning/datasources/influx-datasource.yml

