apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    uid: "b8cb4326-8b98-49d6-8a9c-839e5c32a6a3"
    url: http://influxdb:8086
    basicAuth: false
    isDefault: true
    jsonData:
      version: Flux
      httpMode: "POST"
      defaultBucket: "performance-bucket"
      organization: "test-org"
    secureJsonData:
      token: RQWlUg-S5QtgcPieJHU_WgWTDtDbqobm5nHF9txTxcpI9stRpg4yZCFp3hZmmna9Lnau-_Fn8haHO779iuujiw==
    editable: true
