version: "3.9"

networks:
  monitoring:

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - monitoring
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=test-org
      - DOCKER_INFLUXDB_INIT_USERNAME=test-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=test-password
      - DOCKER_INFLUXDB_INIT_BUCKET=performance-bucket
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin-password
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards/influxdb-dashboard.json:/var/lib/grafana/dashboards/influxdb-dashboard.json
      - ./grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
