version: "3.8"

networks:
  monitoring:

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    hostname: "app-01"
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "cat /proc/1/cmdline | grep telegraf" ]
      interval: 5s
      start_period: 5s
    depends_on:
      - influxdb
      - grafana
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - LOG_FILE=${LOG_FILE}
    command: [ "telegraf", "--config",  "/app/telegraf.conf" ]

  influxdb:
    hostname: "influxdb-01"
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 5s
      start_period: 10s
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_USERNAME=${ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  grafana:
    hostname: "grafana-01"
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 5s
      start_period: 10s
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ./grafana/dashboards/influxdb-dashboard.json:/var/lib/grafana/dashboards/influxdb-dashboard.json
      - ./grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/influx-datasource.yml:/etc/grafana/provisioning/datasources/influx-datasource.yml
